apiVersion: apps/v1
kind: Deployment
metadata:
  name: vreme-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vreme
  template:
    metadata:
      labels:
        app: vreme
    spec:
      containers:
        - image: pockar/vreme:latest
          name: vreme
          ports:
            - containerPort: 8086
              name: server
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "200Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: vreme
spec:
  type: ClusterIP
  ports:
    - port: 8086
      protocol: TCP
      targetPort: server
  selector:
    app: vreme