kumuluzee:
  name: vreme-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/vremeDS
      connection-url: jdbc:postgresql://localhost:5432/vreme
      username: dbuser
      password: postgres
logs:
  config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="Pohodnik">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="70b30c4c-a54e-476a-a5ea-42d916818926-ls.logit.io"
                                port="21053" protocol="udp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info" />
                                    <AppenderRef ref="logstash" level="trace" />
                                </Root>
                            </Loggers>
                        </Configuration>'
